spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classiccardb
    username: salt
    password: secret
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgresql
      mode: never
    output:
      ansi:
        enabled: always
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR