spring:
  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  output:
    ansi:
      enabled: always
  config:
    import: optional:secret.yml
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR